<a href="https://colab.research.google.com/github/urozanska/data-science-bootcamp/blob/main/template.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello collab")#połącz ze środowiskiem uruchomieniowym -> shift enter -> potem tez mozna #file, save a copy in github

Hello collab


In [2]:
#numpy.org - strona biblioteki numpy
#numpy.org/doc - dokumentacja
#01_wprowadzenie/01_numpy_intro.ipynb
import numpy as np
np.__version__

'1.21.6'

In [ ]:
print(dir(np)) #jakie mamy klasy metody atrybuty w tej bibliotece
#jak zapisujemy plik na gicie, to zapisują się razem z wynikami - wynik wywołania tej funkcji zajmuje dużo miejsca więc po wywołaniu i zobaczeniu mozna go zamknąć X-em który pojawia się po lewej stronie od Out-u

In [ ]:
help(np.array)#wyświetlenie pomocy nt funkcji array - PODSTAWOWA FUNCKJA
#funkcja tworzy tablice - help wyświetla nam co możemy podać i też przykłady

podstawowym opiektem b. numpy jest wielowymiarowa tablica. Cechą charakterystyczną jest jednorodnosc elementow - muszą być tego samego typu
wymiary są nazwyane osiami  - mowimy axes
klasa - ndarray

In [ ]:
x = np.array([1, 3]) #tablica jenowymiarowa z elementami 1,3/ inaczej wektor lub punkt w przestrzeni R2
#w środku podana lista czyli troche tablice tworzymy podając liste
x

array([1, 3])

In [ ]:
print(x)

[1 3]


In [ ]:
type(x)#wyświetli typ

numpy.ndarray

In [ ]:
x.ndim #wymiar - ta tablica ma wymiar 1 - 1 wiersz

1

In [ ]:
x.shape #CZESTO #wyświetli (2,) bo mamy 2 elementy - jest to jako tupla 

(2,)

In [ ]:
x.size #liczba elementów tablicy

2

In [ ]:
x.dtype #CZESTO - atrybut ktory okresla typ naszych danych - iliczba calkowita 64bitowa

dtype('int64')

In [ ]:
x = np.array([1.3, 2.3, 1.4])
print(x)
x.dtype
x.shape

[1.3 2.3 1.4]


(3,)

In [ ]:
x.dtype


dtype('float64')

### 2D ARRAY

In [ ]:
x = np.array([[1,2],[-3,1]]) #tablica 2wymiarowa

In [ ]:
x.ndim

2

In [ ]:
x.shape #umiejętnosc operowania na wymiarach macierzy jest bardzo wazna gdybym chciała implementowac siec neuonową w bibliotece numpy - można i jest to wiele operacji na dodawaniu ojejmowaniu itd macerzcy

(2, 2)

In [ ]:
x.dtype

dtype('int64')

In [ ]:
x = np.array([[1,2,4],[4,2,1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [ ]:
x.shape

(2, 3)

3D

In [3]:
x = np.array(
    [[[4, 3, 1],
      [3, 1, 2]],
     
     [[4, 1, 3],
      [4, 2, 1]],
     
     [[3, 2, 1],
      [4, 3, 2]]]
)
x
     

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]],

       [[3, 2, 1],
        [4, 3, 2]]])

In [4]:
print(x)


[[[4 3 1]
  [3 1 2]]

 [[4 1 3]
  [4 2 1]]

 [[3 2 1]
  [4 3 2]]]


In [5]:
x.ndim

3

In [ ]:
x.shape #3,2,3 - 3 tablice, 2 wiersze i 3 kolumny

In [8]:
A = np.array([1,2,3], dtype = 'float') #int, float, complex
A.dtype

dtype('float64')

In [9]:
A = np.array([24, 120, 230], dtype=np.int8)#do tworzenia obrazow - tu np. wystarczy zmienna calkowita 8bitowa
A.dtype
     

dtype('int8')

In [10]:
samezera = np.zeros(shape=(4,10)) #tablica z samych zer 4 wiersze, 10 kolum, domyslmioe typ float
print(samezera)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [13]:
ichoose = np.full(shape=(3,3),fill_value = 3)
print(ichoose)

[[3 3 3]
 [3 3 3]
 [3 3 3]]


In [14]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(start=5,stop=10,step=2)

array([5, 7, 9])

In [18]:
A = np.arange(15)
print(A)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [19]:
A.reshape(3,-1) #zmieni kształt tablicy A - zrobi 3 wiersze,a przez to ze w liczbie kolumn podałam -1 to sam dobierze liczbe potrzbnych kolumn

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [21]:
A.reshape(4,-1) #błąd bo sie nie da tak ulozyc

ValueError: ignored

## OPERACJE NA MACIERZACH
Normalnie np. A+B lub np.add(A,B), A-B lub np.subtract(A,b), A*B = to zwykłe mnożenie po elementac

In [22]:

X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, 2]])
print(X, '\n')
print(Y)
     

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [24]:
X*Y #zwykłe mnożenie

array([[6, 0],
       [2, 0]])

In [25]:
np.dot(X,Y) #mnożenie macierzowe wiersz*kolumna

array([[  3,   6],
       [-12,   0]])

In [27]:
X.dot(Y) #inny zapis - używamy na macierzy X metody dot

array([[  3,   6],
       [-12,   0]])

In [26]:
X@Y #też mnożenie

array([[  3,   6],
       [-12,   0]])

Tworzenie tablic

## Generowanie liczb pseudolosowych

In [28]:
np.random.seed(0)

In [29]:
np.random.randn(10)#z rozkładu normalnego

array([ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799,
       -0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ])

In [30]:
np.random.rand(10)#rozkład jednostajny [0,1)]

array([0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606,
       0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215])

In [31]:
np.random.rand(10,2)#rozkład jednostajny [0,1)]

array([[0.97861834, 0.79915856],
       [0.46147936, 0.78052918],
       [0.11827443, 0.63992102],
       [0.14335329, 0.94466892],
       [0.52184832, 0.41466194],
       [0.26455561, 0.77423369],
       [0.45615033, 0.56843395],
       [0.0187898 , 0.6176355 ],
       [0.61209572, 0.616934  ],
       [0.94374808, 0.6818203 ]])