<a href="https://colab.research.google.com/github/urozanska/data-science-bootcamp/blob/main/template.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello collab")#połącz ze środowiskiem uruchomieniowym -> shift enter -> potem tez mozna #file, save a copy in github

Hello collab


In [3]:
#numpy.org - strona biblioteki numpy
#numpy.org/doc - dokumentacja
#01_wprowadzenie/01_numpy_intro.ipynb
import numpy as np
np.__version__

'1.21.6'

In [ ]:
print(dir(np)) #jakie mamy klasy metody atrybuty w tej bibliotece
#jak zapisujemy plik na gicie, to zapisują się razem z wynikami - wynik wywołania tej funkcji zajmuje dużo miejsca więc po wywołaniu i zobaczeniu mozna go zamknąć X-em który pojawia się po lewej stronie od Out-u

In [ ]:
help(np.array)#wyświetlenie pomocy nt funkcji array - PODSTAWOWA FUNCKJA
#funkcja tworzy tablice - help wyświetla nam co możemy podać i też przykłady

podstawowym opiektem b. numpy jest wielowymiarowa tablica. Cechą charakterystyczną jest jednorodnosc elementow - muszą być tego samego typu
wymiary są nazwyane osiami  - mowimy axes
klasa - ndarray

In [6]:
x = np.array([1, 3]) #tablica jenowymiarowa z elementami 1,3/ inaczej wektor lub punkt w przestrzeni R2
#w środku podana lista czyli troche tablice tworzymy podając liste
x

array([1, 3])

In [7]:
print(x)

[1 3]


In [8]:
type(x)#wyświetli typ

numpy.ndarray

In [9]:
x.ndim #wymiar - ta tablica ma wymiar 1 - 1 wiersz

1

In [10]:
x.shape #CZESTO #wyświetli (2,) bo mamy 2 elementy - jest to jako tupla 

(2,)

In [11]:
x.size #liczba elementów tablicy

2

In [12]:
x.dtype #CZESTO - atrybut ktory okresla typ naszych danych - iliczba calkowita 64bitowa

dtype('int64')

In [13]:
x = np.array([1.3, 2.3, 1.4])
print(x)
x.dtype
x.shape

[1.3 2.3 1.4]


(3,)

In [14]:
x.dtype


dtype('float64')

### 2D ARRAY

In [17]:
x = np.array([[1,2],[-3,1]]) #tablica 2wymiarowa

In [18]:
x.ndim

2

In [19]:
x.shape #umiejętnosc operowania na wymiarach macierzy jest bardzo wazna gdybym chciała implementowac siec neuonową w bibliotece numpy - można i jest to wiele operacji na dodawaniu ojejmowaniu itd macerzcy

(2, 2)

In [20]:
x.dtype

dtype('int64')

In [22]:
x = np.array([[1,2,4],[4,2,1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [23]:
x.shape

(2, 3)